
spring:
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 512
        max-idle: 100
        min-idle: 0
        max-wait: -1
    timeout: 5000
server:
  port: 6097